FROM xqdocker/ubuntu-nginx

#COPY /my/static/content /data/www
COPY $HOME/Projects/deep-change-preview/support/vagrant/root/etc/ssl/private /etc/ssl/private

#RUN apk update
#RUN apk add --no-cache make gcc g++ python
#RUN npm install -g bower grunt karma webpack
#RUN su -c 'cd; ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts;' jhall
#RUN su -c 'cd; cd horizon;' jhall
#RUN su -c 'cd; cd horizon; git pull;' jhall
#RUN su -c 'cd; cd horizon; git checkout master;' jhall
#RUN su -c 'cd; cd horizon; git pull;' jhall
#RUN su -c 'cd; cd horizon; npm install --production --silent' jhall
#RUN apk del make gcc g++ python

#CMD /home/jhall/horizon/start.sh
